name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      solution-path: ${{ steps.set-path.outputs.solution }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/MappingSystem/MappingSystem.sln

      - name: Build Solution
        run: dotnet build src/MappingSystem/MappingSystem.sln --no-restore --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests
        uses: dotnet test test/MappingSystem.Tests/MappingSystem.Tests.csproj --no-build --verbosity normal